apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pipeline-pvc
spec:
  accessModes:
    - ReadWriteOnce # The volume can be mounted as read-write by a single Worker Node
  resources:
    requests:
      storage: 100Mi
