# 1. Workflow Name
name: Simple CI Workflow

# 2. Event Triggers
on:
  push:
    branches: [ main ] # Runs on pushes to the main branch
  pull_request:
    branches: [ main ] # Runs on pull requests targeting the main branch
  workflow_dispatch: # Allows manual triggering from the Actions tab

# 3. Jobs
jobs:
  # Job ID (can be anything descriptive)
  build-and-lint:
    # Runner environment
    runs-on: ubuntu-latest # Specifies the type of machine to run the job on

    # 4. Steps - sequence of tasks
    steps:
      # Action: Checks out our repository code
      - name: Check out repository code
        uses: actions/checkout@v4 # Using a pre-built action from the marketplace

      # Action: Sets up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4 # Another marketplace action
        with:
          python-version: '3.10' # Specify the Python version

      # Install dependencies
      - name: Install dependencies
        run: | # Use 'run' for executing shell commands
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run linter (Flake8)
      - name: Lint with Flake8
        run: |
          # Stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # Exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      # Run a simple test (execute the script)
      - name: Run Python script
        run: python app.py
